// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {http} from '../models';
import {context} from '../models';
import {sql} from '../models';

export function ActualizarCliente(arg1:backend.Cliente):Promise<string>;

export function ActualizarEstadoFacturaCompra(arg1:string,arg2:string):Promise<void>;

export function ActualizarFilaTabla(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean):Promise<backend.OperationResult>;

export function ActualizarPerfilVendedor(arg1:backend.VendedorUpdateRequest):Promise<string>;

export function ActualizarProducto(arg1:backend.ProductoAjusteRequest):Promise<string>;

export function ActualizarProveedor(arg1:backend.Proveedor):Promise<void>;

export function ActualizarStockMasivo(arg1:Array<backend.AjusteStockRequest>):Promise<string>;

export function ActualizarVendedor(arg1:backend.Vendedor):Promise<backend.Vendedor>;

export function AnalizarTabla(arg1:string):Promise<backend.OperationResult>;

export function AuthMiddleware(arg1:http.Handler):Promise<http.Handler>;

export function BeginTx(arg1:context.Context):Promise<sql.Tx>;

export function BuscarFacturasVenta(arg1:string,arg2:number):Promise<Array<backend.FacturaVentaResumen>>;

export function CargarDesdeCSV(arg1:string,arg2:string):Promise<any|any>;

export function Close():Promise<void>;

export function ConfigurarDB(arg1:string):Promise<void>;

export function ContarTransferenciasNoLeidas():Promise<number>;

export function CrearOperacionStock(arg1:sql.Tx,arg2:string,arg3:string,arg4:number,arg5:string,arg6:any):Promise<void>;

export function CrearProveedor(arg1:backend.Proveedor):Promise<void>;

export function DesvincularFactura(arg1:string):Promise<void>;

export function EliminarCliente(arg1:string):Promise<string>;

export function EliminarFilaTabla(arg1:string,arg2:string,arg3:string):Promise<backend.OperationResult>;

export function EliminarProducto(arg1:string):Promise<void>;

export function EliminarProveedor(arg1:string):Promise<void>;

export function EliminarTransferencia(arg1:string):Promise<void>;

export function EliminarTransferencias(arg1:Array<string>):Promise<void>;

export function EliminarVendedor(arg1:string):Promise<string>;

export function Exec(arg1:context.Context,arg2:string,arg3:Array<any>):Promise<sql.Result>;

export function ExisteFacturaCompra(arg1:string,arg2:string):Promise<boolean>;

export function ExisteTransferencia(arg1:string):Promise<boolean>;

export function ExistingEmailIDsSet(arg1:Array<string>):Promise<Record<string, boolean>>;

export function ExportarBDSQL():Promise<backend.OperationResult>;

export function ExportarTablaCSV(arg1:string):Promise<backend.OperationResult>;

export function ExportarTablaSQL(arg1:string):Promise<backend.OperationResult>;

export function GenerarMFA(arg1:string):Promise<backend.MFASetupResponse>;

export function GenerateJWT(arg1:backend.Vendedor):Promise<string>;

export function GetDBStatus():Promise<backend.DBStatusResponse>;

export function GetDatosTabla(arg1:string,arg2:number,arg3:number,arg4:string,arg5:string):Promise<backend.TablePreview>;

export function GetEsquemaTabla(arg1:string):Promise<backend.TableSchema>;

export function GetSetting(arg1:string):Promise<string>;

export function GetTablas():Promise<Array<backend.TableInfo>>;

export function GuardarFacturaCompra(arg1:backend.FacturaCompra):Promise<void>;

export function GuardarTransferencia(arg1:backend.TransferenciaBancolombia):Promise<boolean>;

export function HabilitarMFA(arg1:string,arg2:string):Promise<boolean>;

export function ImportaCSV(arg1:string,arg2:string):Promise<void>;

export function ImportarSQL():Promise<backend.OperationResult>;

export function ImportarTablaCSV(arg1:string):Promise<backend.OperationResult>;

export function ImprimirRecibo(arg1:backend.Factura):Promise<void>;

export function IsSetupMode():Promise<boolean>;

export function LoginVendedor(arg1:backend.LoginRequest):Promise<backend.LoginResponse>;

export function MarcarTodasLeidas():Promise<void>;

export function MarcarTransferenciaLeida(arg1:string):Promise<void>;

export function NewPostgresDB(arg1:string):Promise<sql.DB>;

export function NormalizarStock():Promise<void>;

export function NormalizarStockTodosLosProductos():Promise<string>;

export function ObtenerClientePorID(arg1:string):Promise<backend.Cliente>;

export function ObtenerClientesPaginado(arg1:number,arg2:number,arg3:string,arg4:string,arg5:string):Promise<backend.PaginatedResult>;

export function ObtenerDatosDashboard(arg1:string):Promise<backend.DashboardData>;

export function ObtenerDetalleFactura(arg1:string):Promise<backend.Factura>;

export function ObtenerDetalleFacturaCompra(arg1:string):Promise<backend.FacturaCompra>;

export function ObtenerFacturasCompraPaginado(arg1:number,arg2:number,arg3:string,arg4:string,arg5:string):Promise<backend.FacturasCompraResponse>;

export function ObtenerFacturasPaginado(arg1:number,arg2:number,arg3:string,arg4:string,arg5:string):Promise<backend.PaginatedResult>;

export function ObtenerFechasConVentas():Promise<Array<string>>;

export function ObtenerHistorialStock(arg1:string):Promise<Array<backend.OperacionStock>>;

export function ObtenerProductoPorUUID(arg1:string):Promise<backend.Producto>;

export function ObtenerProductosPaginado(arg1:number,arg2:number,arg3:string,arg4:string,arg5:string):Promise<backend.PaginatedResult>;

export function ObtenerProveedorPorUUID(arg1:string):Promise<backend.Proveedor>;

export function ObtenerProveedoresConEstadisticas(arg1:number,arg2:number,arg3:string):Promise<backend.ProveedoresStatsResponse>;

export function ObtenerProveedoresPaginado(arg1:number,arg2:number,arg3:string):Promise<backend.PaginatedResult>;

export function ObtenerReporteVentasRango(arg1:string,arg2:string):Promise<backend.ReporteVentas>;

export function ObtenerResumenCompras(arg1:string,arg2:string):Promise<backend.ResumenCompras>;

export function ObtenerResumenInventario():Promise<backend.ResumenInventario>;

export function ObtenerTopProductosDeProveedor(arg1:string,arg2:number):Promise<Array<backend.ProductoComprado>>;

export function ObtenerTransferenciasPaginado(arg1:number,arg2:number,arg3:boolean,arg4:string,arg5:string):Promise<backend.TransferenciasResponse>;

export function ObtenerVendedoresPaginado(arg1:number,arg2:number,arg3:string,arg4:string,arg5:string):Promise<backend.PaginatedResult>;

export function Query(arg1:context.Context,arg2:string,arg3:Array<any>):Promise<sql.Rows>;

export function QueryRow(arg1:context.Context,arg2:string,arg3:Array<any>):Promise<sql.Row>;

export function RegistrarCliente(arg1:backend.Cliente):Promise<backend.Cliente>;

export function RegistrarCompra(arg1:backend.CompraRequest):Promise<backend.Compra>;

export function RegistrarProducto(arg1:backend.NuevoProducto):Promise<backend.Producto>;

export function RegistrarVendedor(arg1:backend.Vendedor):Promise<backend.Vendedor>;

export function RegistrarVenta(arg1:backend.VentaRequest):Promise<backend.Factura>;

export function ResetearTodaLaData():Promise<string>;

export function SelectFile():Promise<string>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function SincronizarProveedoresDesdeFacturas():Promise<number>;

export function Startup(arg1:context.Context):Promise<void>;

export function TestDBConnection(arg1:string):Promise<void>;

export function TruncarTabla(arg1:string):Promise<backend.OperationResult>;

export function UpsertProveedorPorNIT(arg1:string,arg2:string):Promise<void>;

export function VacuumTabla(arg1:string):Promise<backend.OperationResult>;

export function VerificarImpresora():Promise<boolean>;

export function VerificarLoginMFA(arg1:string,arg2:string):Promise<backend.LoginResponse>;

export function VincularFactura(arg1:string,arg2:string,arg3:string):Promise<void>;
