// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {context} from '../models';

export function BuscarFacturasVenta(arg1:string):Promise<Array<backend.FacturaVentaResumen>>;

export function ContarNoLeidas():Promise<number>;

export function DesvincularFactura(arg1:string):Promise<void>;

export function EliminarTransferencia(arg1:string):Promise<void>;

export function EliminarTransferencias(arg1:Array<string>):Promise<void>;

export function EstadoAuth():Promise<backend.BancolombiaAuthStatus>;

export function GetAutoPolling():Promise<backend.BancolombiaAutoPollingState>;

export function GetSyncProgress():Promise<backend.BancolombiaProgressState>;

export function IniciarOAuth2():Promise<string>;

export function MarcarLeida(arg1:string):Promise<void>;

export function MarcarTodasLeidas():Promise<void>;

export function ObtenerTransferencias(arg1:number,arg2:number,arg3:boolean,arg4:string,arg5:string):Promise<backend.TransferenciasResponse>;

export function RevocarAuth():Promise<void>;

export function SetAutoPolling(arg1:boolean):Promise<void>;

export function Shutdown():Promise<void>;

export function SincronizarConPeriodo(arg1:backend.BancolombiaOpcionesPeriodo):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function VerificarAhora():Promise<void>;

export function VincularFactura(arg1:string,arg2:string,arg3:string):Promise<void>;
