// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {context} from '../models';

export function ActualizarCliente(arg1:backend.Cliente):Promise<string>;

export function ActualizarProducto(arg1:backend.Producto):Promise<string>;

export function ActualizarVendedor(arg1:backend.Vendedor):Promise<string>;

export function BuscarProductos(arg1:string):Promise<Array<backend.Producto>>;

export function EliminarCliente(arg1:number):Promise<string>;

export function EliminarProducto(arg1:number):Promise<string>;

export function EliminarVendedor(arg1:number):Promise<string>;

export function ObtenerClientes():Promise<Array<backend.Cliente>>;

export function ObtenerDetalleFactura(arg1:number):Promise<backend.Factura>;

export function ObtenerFacturas():Promise<Array<backend.Factura>>;

export function ObtenerProductos():Promise<Array<backend.Producto>>;

export function ObtenerVendedores():Promise<Array<backend.Vendedor>>;

export function RegistrarCliente(arg1:backend.Cliente):Promise<string>;

export function RegistrarProducto(arg1:backend.Producto):Promise<string>;

export function RegistrarVendedor(arg1:backend.Vendedor):Promise<string>;

export function RegistrarVenta(arg1:backend.VentaRequest):Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;
