// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {context} from '../models';

export function EjecutarBackupAhora():Promise<backend.DriveBackupResult>;

export function EliminarBackup(arg1:string):Promise<void>;

export function EstadoAuthDrive():Promise<backend.DriveAuthStatus>;

export function GetAutoBackup():Promise<backend.DriveAutoBackupState>;

export function IniciarOAuth2Drive():Promise<string>;

export function ListarBackups():Promise<Array<backend.DriveBackupFile>>;

export function RevocarAuthDrive():Promise<void>;

export function SetAutoBackup(arg1:boolean):Promise<void>;

export function Shutdown():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
