// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActualizarEstadoFacturaCompra(arg1, arg2) {
  return window['go']['backend']['GmailService']['ActualizarEstadoFacturaCompra'](arg1, arg2);
}

export function ConfigDir() {
  return window['go']['backend']['GmailService']['ConfigDir']();
}

export function EnriquecerDescripciones() {
  return window['go']['backend']['GmailService']['EnriquecerDescripciones']();
}

export function EstadoAuth() {
  return window['go']['backend']['GmailService']['EstadoAuth']();
}

export function GetGmailSyncProgress() {
  return window['go']['backend']['GmailService']['GetGmailSyncProgress']();
}

export function GuardarCredenciales(arg1) {
  return window['go']['backend']['GmailService']['GuardarCredenciales'](arg1);
}

export function IniciarOAuth2() {
  return window['go']['backend']['GmailService']['IniciarOAuth2']();
}

export function ObtenerCredenciales() {
  return window['go']['backend']['GmailService']['ObtenerCredenciales']();
}

export function ObtenerDetalleFacturaCompra(arg1) {
  return window['go']['backend']['GmailService']['ObtenerDetalleFacturaCompra'](arg1);
}

export function ObtenerFacturasCompra(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['GmailService']['ObtenerFacturasCompra'](arg1, arg2, arg3, arg4, arg5);
}

export function ObtenerProveedoresConEstadisticas(arg1, arg2, arg3) {
  return window['go']['backend']['GmailService']['ObtenerProveedoresConEstadisticas'](arg1, arg2, arg3);
}

export function ObtenerResumenCompras(arg1, arg2) {
  return window['go']['backend']['GmailService']['ObtenerResumenCompras'](arg1, arg2);
}

export function ObtenerTopProductosDeProveedor(arg1, arg2) {
  return window['go']['backend']['GmailService']['ObtenerTopProductosDeProveedor'](arg1, arg2);
}

export function RevocarAuth() {
  return window['go']['backend']['GmailService']['RevocarAuth']();
}

export function SincronizarConOpciones(arg1) {
  return window['go']['backend']['GmailService']['SincronizarConOpciones'](arg1);
}

export function SincronizarFacturas() {
  return window['go']['backend']['GmailService']['SincronizarFacturas']();
}

export function SincronizarProveedoresDesdeFacturas() {
  return window['go']['backend']['GmailService']['SincronizarProveedoresDesdeFacturas']();
}

export function Startup(arg1) {
  return window['go']['backend']['GmailService']['Startup'](arg1);
}
