// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {context} from '../models';

export function ActualizarEstadoFacturaCompra(arg1:string,arg2:string):Promise<void>;

export function ConfigDir():Promise<string>;

export function EnriquecerDescripciones():Promise<backend.EnriquecerResult>;

export function EstadoAuth():Promise<backend.GmailAuthStatus>;

export function GetGmailSyncProgress():Promise<backend.GmailSyncProgress>;

export function GuardarCredenciales(arg1:string):Promise<void>;

export function IniciarOAuth2():Promise<string>;

export function ObtenerCredenciales():Promise<backend.CredencialesInfo>;

export function ObtenerDetalleFacturaCompra(arg1:string):Promise<backend.FacturaCompra>;

export function ObtenerFacturasCompra(arg1:number,arg2:number,arg3:string,arg4:string,arg5:string):Promise<backend.FacturasCompraResponse>;

export function ObtenerProveedoresConEstadisticas(arg1:number,arg2:number,arg3:string):Promise<backend.ProveedoresStatsResponse>;

export function ObtenerResumenCompras(arg1:string,arg2:string):Promise<backend.ResumenCompras>;

export function ObtenerTopProductosDeProveedor(arg1:string,arg2:number):Promise<Array<backend.ProductoComprado>>;

export function RevocarAuth():Promise<void>;

export function SincronizarConOpciones(arg1:backend.SyncOptions):Promise<void>;

export function SincronizarFacturas():Promise<void>;

export function SincronizarProveedoresDesdeFacturas():Promise<number>;

export function Startup(arg1:context.Context):Promise<void>;
